services:

    redis:
        image: redis:latest
        restart: always
        ports:
            - 6379:6379
        healthcheck:
            test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
        networks:
            - scm

    database:
        image: postgres:15.7-alpine
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=application
        volumes:
            # Postgres Data Folder
            - ./runtime/database/data:/var/lib/postgresql/data
            # Init the seed data from postgres dump file
            - ./db-seed-data/initdb:/docker-entrypoint-initdb.d/
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U postgres']
            interval: 10s
            timeout: 5s
            retries: 5
        ports:
            - 5432:5432
        networks:
            - scm

    pgadmin:
        image: dpage/pgadmin4:latest
        restart: always
        user: root
        environment:
            PGADMIN_DEFAULT_EMAIL: db@muyan.cloud
            PGADMIN_DEFAULT_PASSWORD: secret
            PGADMIN_LISTEN_PORT: 80
            PGADMIN_SERVER_JSON_FILE: /pgadmin4/config/servers.json
        ports:
            - "5433:80"
        volumes:
            - ./runtime/pgadmin/data:/var/lib/pgadmin
            - ./runtime/pgadmin/config:/pgadmin4/config
            - ./runtime/pgadmin/log:/var/log/pgadmin
            - ./runtime/pgadmin/pgpass:/var/lib/pgadmin/storage/db_muyan.cloud/pgpass
        depends_on:
            - database
        networks:
            - scm

    client:
        image: muyantech/frontend:latest
        restart: always
        ports:
            - 3000:80
        working_dir: /usr/share/nginx/html
        stdin_open: true
        depends_on:
            - server
        networks:
            - scm

    server:
        image: muyantech/backend:latest
        restart: always
        environment:
            # 数据库连接地址信息
            # Database connection
            - JDBC_DATABASE_URL=jdbc:postgresql://database:5432/application
            # 数据库用户名
            # Database username
            - JDBC_DATABASE_USERNAME=postgres
            # 数据库密码
            # Database password
            - JDBC_DATABASE_PASSWORD=password
            # 种子数据文件夹，需要挂载
            # Seed data folder, need to be mounted
            - SEED_DATA_FOLDER=/app/plugin/data
            # Redis连接地址
            # Redis connection
            - REDIS_URL=redis://redis:6379
            # Java 远程调试端口
            # Java remote debugging port
            - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005

            # 以下两个参数 **请勿** 在不了解含义的情况下修改
            # Please **do not** modify the following two parameters without understanding the meaning
            # 默认运行的 grails env
            # Default running grails env
            - GRAILS_ENV=development
            # 默认运行的租户 tenant
            # Default running tenant
            - TENANT_ID=muyan
        volumes:
            # 本地的插件开发路径，mount 到 docker 容器中的 /app/plugin
            - ./server:/app/plugin
            # 开发过程中上传的附件的保存路径
            # The path to save the attachments uploaded during development
            - ./runtime/attachments:/app/attachments

        ports:
            # 8080 is the default port for backend server
            - 8080:8080
            # 5005 is the default port for remote debugging
            - 5005:5005
        stdin_open: true
        depends_on:
            - database
            - redis
        networks:
            - scm

networks:
  scm:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.57.0/24
