# Gradle build.

name: Build and Publish Reports

on: [push]

jobs:

  # Label of the container job
  Build:
    name: Build package and upload artifacts
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:

      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt-openj9'
          java-version: 11

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}

      - name: Build Package
        run: |
          ./gradlew build --info
          ./gradlew packageMuyanPlugin --info
          ./gradlew packageSeedData --info

      - name: Prepare Seed Data Package
        run: |
          ./gradlew packageSeedData --info

      - name: Prepare Plugin Package
        run: |
          ./gradlew build --info
          ./gradlew packageMuyanPlugin --info
          ./gradlew packageSeedData --info

      - name: Upload Seed Data Package
        uses: actions/upload-artifact@v2
        with:
          # Artifact name
          name: Seed Data Package
          # Directory containing files to upload
          path: build/muyan/data.zip

      - name: Upload Plugin Package
        uses: actions/upload-artifact@v2
        with:
          # Artifact name
          name: Plugin Package
          # Directory containing files to upload
          path: example/build/muyan-plugin/DemoPlugin-0.0.1.myp

  UnitTest:
    name: Unit test and upload reports
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt-openj9'
          java-version: 11

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}

      - name: Run Unit Tests
        run: |
          ./gradlew test --info

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: build/test-results/**/*.xml
